// Abhay Pharma - 50 Premium Pharmacy Products Database
const PRODUCTS = [
  // --- Category: Prescription Medicines ---
  {
    id: "p1",
    uses: "Fever reduction (antipyretic) and relief of mild to moderate pain like headache, toothache, muscle ache, and joint pain.",
    precautions: "Avoid alcohol consumption while taking this tablet. High doses can cause severe liver damage. Consult your doctor if pregnant or lactating.",
    name: "Dolo 650 Tablet",
    brand: "Micro Labs",
    price: 35.00,
    discount: 10,
    rating: 4.8,
    reviewsCount: 3120,
    description: "Dolo 650 Tablet is a widely prescribed analgesic (painkiller) and antipyretic (fever-reducing) medicine. It contains Paracetamol, which helps in relieving mild to moderate pain and reducing body temperature during fever.",
    benefits: "Effective in reducing fever and relieving mild to moderate pain such as headache, toothache, muscle ache, and joint pain.",
    dosage: "As directed by the physician. Usually 1 tablet every 4-6 hours, not exceeding 4 tablets in 24 hours.",
    sideEffects: "Allergic skin reactions, nausea, vomiting (rare when taken in recommended doses). Excessive dosage may cause severe liver damage.",
    usage: "Take this medicine with or after food to avoid stomach irritation. Swallow it whole with a glass of water.",
    composition: "Paracetamol IP 650mg",
    manufacturer: "Micro Labs Ltd",
    category: "Prescription Medicines",
    image: "https://images.apollo247.in/pub/media/catalog/product/d/o/dol0026_1-.jpg",
    prescriptionRequired: true,
    stock: 240
  },
  {
    id: "p2",
    uses: "Management of type 2 diabetes mellitus to help control and lower blood glucose levels.",
    precautions: "Monitor kidney and liver function regularly. Avoid heavy alcohol intake to reduce the risk of lactic acidosis. Take with meals to avoid stomach upset.",
    name: "Glycomet 500mg Tablet",
    brand: "USV Pvt Ltd",
    price: 24.50,
    discount: 5,
    rating: 4.7,
    reviewsCount: 1420,
    description: "Glycomet 500 Tablet contains Metformin, an oral antidiabetic medicine that belongs to the biguanides class. It helps control blood sugar levels in people with type 2 diabetes mellitus.",
    benefits: "Lowers blood glucose levels, improves insulin sensitivity, and reduces the risk of long-term diabetes complications.",
    dosage: "Take exactly as prescribed by your doctor, usually with meals to minimize gastrointestinal side effects.",
    sideEffects: "Nausea, vomiting, diarrhea, abdominal pain, loss of appetite, and a metallic taste in the mouth.",
    usage: "Swallow the tablet whole. Do not crush or chew it. Take it daily at the same time.",
    composition: "Metformin Hydrochloride IP 500mg",
    manufacturer: "USV Private Limited",
    category: "Prescription Medicines",
    image: "https://images.apollo247.in/pub/media/catalog/product/G/L/GLY0028_1_1.jpg",
    prescriptionRequired: true,
    stock: 180
  },
  {
    id: "p3",
    uses: "Treatment of bacterial infections including infections of the respiratory tract, throat, sinus, ear, and urinary tract.",
    precautions: "Complete the full course even if you feel better. Avoid if you have a known history of penicillin allergy. Inform doctor if skin rash or severe diarrhea occurs.",
    name: "Novamox 500mg Capsule",
    brand: "Cipla",
    price: 112.00,
    discount: 15,
    rating: 4.6,
    reviewsCount: 980,
    description: "Novamox 500 Capsule is a broad-spectrum penicillin-type antibiotic used to treat a wide variety of bacterial infections, including throat, sinus, ear, urinary tract, and respiratory tract infections.",
    benefits: "Stops the growth of bacteria causing the infection. Fast recovery when the complete course is taken.",
    dosage: "Complete the full course prescribed by your physician. Usually 1 capsule three times a day.",
    sideEffects: "Nausea, diarrhea, skin rash, itching, and vomiting.",
    usage: "Can be taken with or without food. Drink plenty of fluids while taking this medication.",
    composition: "Amoxicillin Trihydrate IP equivalent to Amoxicillin 500mg",
    manufacturer: "Cipla Ltd",
    category: "Prescription Medicines",
    image: "https://images.apollo247.in/pub/media/catalog/product/n/o/nov0041.jpg",
    prescriptionRequired: true,
    stock: 120
  },
  {
    id: "p4",
    uses: "Lowering cholesterol levels (LDL and triglycerides) and reducing the risk of heart diseases like heart attack and stroke.",
    precautions: "Avoid during pregnancy and breastfeeding. Report any unexplained muscle pain or weakness immediately. Limit grapefruit juice consumption.",
    name: "Lipvas 10mg Tablet",
    brand: "Cipla",
    price: 85.00,
    discount: 8,
    rating: 4.7,
    reviewsCount: 1560,
    description: "Lipvas 10 Tablet contains Atorvastatin, which belongs to a group of medicines called statins. It is used to lower cholesterol and to reduce the risk of heart disease.",
    benefits: "Reduces 'bad' cholesterol (LDL) and triglycerides, increases 'good' cholesterol (HDL), and prevents heart attacks and strokes.",
    dosage: "Once daily, preferably at bedtime, or as recommended by the cardiologist.",
    sideEffects: "Muscle pain, weakness, headache, abdominal pain, and mild elevation of liver enzymes.",
    usage: "Take it with or without food. Avoid high-fat meals and grapefruit juice during treatment.",
    composition: "Atorvastatin Calcium IP equivalent to Atorvastatin 10mg",
    manufacturer: "Cipla Ltd",
    category: "Prescription Medicines",
    image: "https://images.apollo247.in/pub/media/catalog/product/L/I/LIP0052_1_1.jpg",
    prescriptionRequired: true,
    stock: 300
  },
  {
    id: "p5",
    uses: "Prevention of asthma attacks and relief of seasonal allergic rhinitis symptoms like sneezing, runny nose, and itchy eyes.",
    precautions: "Do not use to treat acute asthma attacks; use a rescue inhaler instead. Report any mood or behavior changes to your doctor immediately.",
    name: "Montair 10mg Tablet",
    brand: "Cipla",
    price: 168.00,
    discount: 12,
    rating: 4.8,
    reviewsCount: 2040,
    description: "Montair 10 Tablet is a leukotriene receptor antagonist. It is used to prevent asthma attacks and relieve symptoms of seasonal allergic rhinitis (sneezing, runny nose).",
    benefits: "Reduces swelling in the airways, making breathing easier. Prevents exercise-induced asthma.",
    dosage: "Typically 1 tablet daily in the evening, with or without food, or as prescribed.",
    sideEffects: "Headache, abdominal pain, mild drowsiness, and upper respiratory tract symptoms.",
    usage: "Take regular doses at night, even if you are not experiencing asthma symptoms.",
    composition: "Montelukast Sodium IP equivalent to Montelukast 10mg",
    manufacturer: "Cipla Ltd",
    category: "Prescription Medicines",
    image: "https://images.apollo247.in/pub/media/catalog/product/M/O/MON0034_1_1.jpg",
    prescriptionRequired: true,
    stock: 190
  },
  {
    id: "p6",
    uses: "Treatment of high blood pressure (hypertension) and chest pain (angina).",
    precautions: "May cause ankle swelling or dizziness. Do not stop taking this medication suddenly. Avoid driving if feeling dizzy.",
    name: "Amlokind 5mg Tablet",
    brand: "Mankind Pharma",
    price: 18.00,
    discount: 5,
    rating: 4.5,
    reviewsCount: 890,
    description: "Amlokind 5 Tablet contains Amlodipine, a calcium channel blocker. It is used to treat high blood pressure (hypertension) and prevent angina (heart-related chest pain).",
    benefits: "Relaxes blood vessels, lowering blood pressure and reducing the workload of the heart.",
    dosage: "Once daily, at the same time every day, or as advised by your physician.",
    sideEffects: "Ankle swelling, headache, tiredness, dizziness, and warmth in the face/neck (flushing).",
    usage: "Can be taken with or without food. Avoid sudden discontinuation without medical consultation.",
    composition: "Amlodipine Besylate IP equivalent to Amlodipine 5mg",
    manufacturer: "Mankind Pharma Ltd",
    category: "Prescription Medicines",
    image: "https://cdn01.pharmeasy.in/dam/products/G14460/amlokind-5mg-strip-of-15-tablets-7-1650021203.jpg",
    prescriptionRequired: true,
    stock: 450
  },
  {
    id: "p7",
    uses: "Treatment of gastroesophageal reflux disease (GERD), acid reflux, peptic ulcers, and acidity.",
    precautions: "Take 1 hour before the first meal of the day. Long-term use may cause magnesium deficiency; consult doctor for continuous use.",
    name: "Pan 40mg Tablet",
    brand: "Alkem Labs",
    price: 145.00,
    discount: 10,
    rating: 4.7,
    reviewsCount: 2310,
    description: "Pan 40 Tablet is a proton pump inhibitor (PPI) containing Pantoprazole. It reduces the amount of acid produced in the stomach and is used to treat GERD, ulcers, and acid reflux.",
    benefits: "Relieves heartburn, acidity, difficulty swallowing, and heals acid-induced damage to the stomach and esophagus.",
    dosage: "1 tablet daily in the morning, 1 hour before breakfast/first meal, or as prescribed.",
    sideEffects: "Headache, diarrhea, nausea, flatulence, and dizziness.",
    usage: "Swallow the tablet whole with water. Do not crush, chew, or break the tablet.",
    composition: "Pantoprazole Sodium Sesquihydrate IP equivalent to Pantoprazole 40mg",
    manufacturer: "Alkem Laboratories Ltd",
    category: "Prescription Medicines",
    image: "https://cdn01.pharmeasy.in/dam/products/I00306/pan-40mg-strip-of-15-tablets-2-1742470192.jpg",
    prescriptionRequired: true,
    stock: 280
  },
  {
    id: "p8",
    uses: "Treatment of bacterial infections of the ears, throat, sinus, respiratory tract, and skin.",
    precautions: "Do not take antacids containing aluminum or magnesium within 2 hours of taking this medicine. Complete the full course.",
    name: "Azax 500mg Tablet",
    brand: "Cipla",
    price: 119.00,
    discount: 15,
    rating: 4.6,
    reviewsCount: 1150,
    description: "Azax 500 Tablet contains Azithromycin, a macrolide antibiotic. It is highly effective in treating various bacterial infections of the respiratory tract, skin, ears, and throat.",
    benefits: "Short 3-to-5 day course provides effective relief from bacterial infections. Stops bacterial protein synthesis.",
    dosage: "Once daily, exactly as prescribed by the doctor, typically for 3 or 5 days.",
    sideEffects: "Diarrhea, nausea, vomiting, abdominal discomfort, and temporary hearing changes (rare).",
    usage: "Preferably taken 1 hour before or 2 hours after a meal with plenty of water.",
    composition: "Azithromycin Dihydrate IP equivalent to Azithromycin 500mg",
    manufacturer: "Cipla Ltd",
    category: "Prescription Medicines",
    image: "https://onemg.gumlet.io/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/cad8e89a77dc4e49b08f95496281a2ad.jpg",
    prescriptionRequired: true,
    stock: 140
  },

  // --- Category: OTC Medicines ---
  {
    id: "p9",
    uses: "Fast-acting relief from severe headaches, migraines, toothaches, and musculoskeletal pain.",
    precautions: "Do not exceed the recommended dose. Contains caffeine; limit intake of tea, coffee, and energy drinks to avoid restlessness.",
    name: "Crocin Pain Relief",
    brand: "GlaxoSmithKline",
    price: 42.00,
    discount: 5,
    rating: 4.6,
    reviewsCount: 1840,
    description: "Crocin Pain Relief is a combination of Paracetamol and Caffeine. Caffeine enhances the analgesic effect of Paracetamol, providing fast and targeted relief from severe headaches, migraines, and musculoskeletal pain.",
    benefits: "Provides double-action relief from headaches, migraines, joint pain, and toothaches. Non-drowsy formulation.",
    dosage: "1-2 tablets every 4-6 hours, not exceeding 8 tablets in 24 hours.",
    sideEffects: "Insomnia or restlessness (due to caffeine content if taken near bedtime), increased heart rate.",
    usage: "Swallow with water. Limit other caffeine consumption during use to avoid nervousness.",
    composition: "Paracetamol IP 650mg, Caffeine Anhydrous IP 50mg",
    manufacturer: "GSK Consumer Healthcare",
    category: "OTC Medicines",
    image: "https://cdn01.pharmeasy.in/dam/products_otc/269415/crocin-pain-relief-strip-of-15-tablets-1-1701935215.jpg",
    prescriptionRequired: false,
    stock: 500
  },
  {
    id: "p10",
    uses: "Relief of inflammatory pain, joint pain, menstrual cramps, swelling, and fever.",
    precautions: "Always take with food or milk. Avoid if you have a history of stomach ulcers, kidney disease, or asthma.",
    name: "Brufen 400mg Tablet",
    brand: "Abbott",
    price: 15.00,
    discount: 5,
    rating: 4.4,
    reviewsCount: 750,
    description: "Brufen 400 Tablet is a non-steroidal anti-inflammatory drug (NSAID) containing Ibuprofen. It relieves inflammation, swelling, fever, and moderate-to-severe pain.",
    benefits: "Reduces painful swelling, joint stiffness, menstrual pain, and body aches efficiently.",
    dosage: "1 tablet after meals, 2-3 times daily, or as required. Consult a doctor for prolonged use.",
    sideEffects: "Acidity, heartburn, stomach upset, nausea, and mild indigestion.",
    usage: "Always take with food or milk to prevent stomach irritation.",
    composition: "Ibuprofen IP 400mg",
    manufacturer: "Abbott India Ltd",
    category: "OTC Medicines",
    image: "https://images.apollo247.in/pub/media/catalog/product/b/r/bru0003_.jpg",
    prescriptionRequired: false,
    stock: 400
  },
  {
    id: "p11",
    uses: "Relief from allergic symptoms like runny nose, sneezing, hives, skin itching, and watery eyes.",
    precautions: "May cause mild drowsiness. Avoid driving or operating machinery after taking. Limit alcohol consumption.",
    name: "Cetzine 10mg Tablet",
    brand: "GlaxoSmithKline",
    price: 20.00,
    discount: 10,
    rating: 4.5,
    reviewsCount: 920,
    description: "Cetzine contains Cetirizine, a highly effective non-sedating antihistamine. It is used to treat allergy symptoms such as running nose, sneezing, watery eyes, and hives.",
    benefits: "Provides 24-hour relief from allergies without major drowsiness. Works rapidly within an hour.",
    dosage: "1 tablet daily at night or as recommended.",
    sideEffects: "Mild sleepiness, dry mouth, headache, and fatigue.",
    usage: "Swallow whole with water. Can be taken with or without food.",
    composition: "Cetirizine Hydrochloride IP 10mg",
    manufacturer: "GSK India",
    category: "OTC Medicines",
    image: "https://www.netmeds.com/images/product-v1/600x600/10452/cetzine_10mg_tablet_15_s_0_1.jpg",
    prescriptionRequired: false,
    stock: 350
  },
  {
    id: "p12",
    uses: "Rapid relief from acidity, gas, bloating, heartburn, and stomach indigestion.",
    precautions: "Shake the bottle well. Do not consume other medicines within 2 hours of taking this antacid as it may block absorption.",
    name: "Digene Antacid Liquid (Mixed Fruit)",
    brand: "Abbott",
    price: 155.00,
    discount: 10,
    rating: 4.7,
    reviewsCount: 3100,
    description: "Digene Gel Mixed Fruit flavor provides quick, soothing relief from acidity, gas, heartburn, and stomach discomfort. It neutralizes stomach acid and forms a protective coating.",
    benefits: "Fast-acting relief with a sugar-free, refreshing mixed fruit flavor. Reduces flatulence and bloating.",
    dosage: "2-4 teaspoons (10ml to 20ml) after meals or at bedtime, or as recommended.",
    sideEffects: "Constipation or diarrhea (if taken in very large doses).",
    usage: "Shake the bottle well before use. Do not dilute with water.",
    composition: "Magnesium Hydroxide 185mg, Simethicone 25mg, Aluminum Hydroxide Gel 830mg",
    manufacturer: "Abbott India Ltd",
    category: "OTC Medicines",
    image: "https://onemg.gumlet.io/a_ignore,c_fit,q_auto,f_auto/cropped/ofuezxzkkiwn1j1zxjw2.jpg",
    prescriptionRequired: false,
    stock: 180
  },
  {
    id: "p13",
    uses: "Relief of sore throat, throat irritation, dry cough, and minor mouth/throat infections.",
    precautions: "Do not chew or swallow whole; allow to dissolve slowly in the mouth. Not recommended for children under 6 years.",
    name: "Cofsils Orange Lozenges",
    brand: "Cipla Health",
    price: 30.00,
    discount: 0,
    rating: 4.6,
    reviewsCount: 1480,
    description: "Cofsils Lozenges contain powerful antibacterial and antiseptic ingredients that soothe dry or irritated throats and provide instant relief from coughing.",
    benefits: "Soothes sore throat in 3 minutes. Provides relief from throat irritation and minor infections.",
    dosage: "Dissolve one lozenge slowly in the mouth every 3 hours, up to 8 lozenges per day.",
    sideEffects: "No notable side effects. Avoid giving to children below 6 years.",
    usage: "Let the lozenge dissolve slowly in your mouth. Do not chew or swallow it whole.",
    composition: "Amylmetacresol BP 0.6mg, Dichlorobenzyl Alcohol 1.2mg",
    manufacturer: "Cipla Health Ltd",
    category: "OTC Medicines",
    image: "https://images.apollo247.in/pub/media/catalog/product/C/O/COF0039_1.jpg",
    prescriptionRequired: false,
    stock: 600
  },
  {
    id: "p14",
    uses: "Temporary relief from nasal congestion, cough, headache, and body ache due to common colds.",
    precautions: "For external use only. Do not apply directly to nostrils or broken skin. Do not heat or expose to open flame.",
    name: "Vicks Vaporub 50g",
    brand: "Procter & Gamble",
    price: 165.00,
    discount: 8,
    rating: 4.8,
    reviewsCount: 4200,
    description: "Vicks Vaporub is a classic topical ointment containing natural ingredients like Menthol, Camphor, and Eucalyptus Oil. It provides relief from cold symptoms, nasal congestion, and muscle aches.",
    benefits: "Provides relief from 6 cold symptoms: cough, nasal congestion, headache, body ache, muscle stiffness, and sore throat.",
    dosage: "Apply liberally to chest, throat, and back. Repeat up to 3-4 times a day.",
    sideEffects: "Mild skin redness or irritation in rare cases.",
    usage: "Rub on skin. Alternatively, add 2 teaspoons to hot (not boiling) water and inhale the steam.",
    composition: "Menthol 2.82g, Camphor 5.25g, Eucalyptus Oil 1.35g",
    manufacturer: "Procter & Gamble Hygiene and Health Care Ltd",
    category: "OTC Medicines",
    image: "https://onemg.gumlet.io/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/37ab010b61154c468c1348fd8c4e24af.jpg",
    prescriptionRequired: false,
    stock: 250
  },

  // --- Category: Diabetes Care ---
  {
    id: "p15",
    uses: "Self-monitoring of blood glucose levels in capillary blood for diabetes management.",
    precautions: "Wash and dry hands before testing. Do not share lancing devices. Check strip expiry dates before inserting.",
    name: "Accu-Chek Active Glucometer",
    brand: "Roche Diagnostics",
    price: 999.00,
    discount: 33,
    rating: 4.7,
    reviewsCount: 5200,
    description: "The Accu-Chek Active Blood Glucose Meter is a highly accurate, easy-to-use digital device designed for self-testing. It provides reliable blood sugar readings within 5 seconds.",
    benefits: "No coding required. Simple two-button operation. Memory capacity of 500 readings with average results.",
    dosage: "Use as needed to track blood glucose levels, typically before and after meals.",
    sideEffects: "None. Follow safety instructions while drawing blood samples.",
    usage: "Insert a test strip, apply a small blood drop to the green field, and read the result on the digital screen.",
    composition: "1 Glucometer Unit, 1 Lancing Device, 10 Lancets, 10 Test Strips",
    manufacturer: "Roche Diabetes Care",
    category: "Diabetes Care",
    image: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/hx2gxivwmeoxxxsc1hix.png",
    prescriptionRequired: false,
    stock: 95
  },
  {
    id: "p16",
    uses: "Quantitative measurement of glucose in fresh capillary blood samples using Accu-Chek Active meter.",
    precautions: "Store in a cool, dry place between 2°C and 30°C. Close the vial tightly immediately after removing a test strip.",
    name: "Accu-Chek Active Test Strips (50s)",
    brand: "Roche Diagnostics",
    price: 975.00,
    discount: 15,
    rating: 4.8,
    reviewsCount: 7800,
    description: "Accu-Chek Active Test Strips are designed for use with the Accu-Chek Active Glucometer. They help in measuring glucose levels in capillary blood easily and accurately.",
    benefits: "Top-rated accuracy matching laboratory standards. Visual double-check feature to confirm reading.",
    dosage: "Single use per strip. Store in a cool, dry place.",
    sideEffects: "None.",
    usage: "Insert the strip into the meter. Apply blood when the drop symbol flashes.",
    composition: "50 Blood Glucose Test Strips",
    manufacturer: "Roche Diabetes Care",
    category: "Diabetes Care",
    image: "https://onemg.gumlet.io/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/e526fb87595348dc98d0baba04684f8c.jpg",
    prescriptionRequired: false,
    stock: 210
  },
  {
    id: "p17",
    uses: "Sugar substitute for sweetening tea, coffee, beverages, and desserts for diabetics and weight watchers.",
    precautions: "Not recommended for children and pregnant women. Safe for diabetics but consult a nutritionist for daily limits.",
    name: "Sugar Free Gold Sweetener",
    brand: "Zydus Wellness",
    price: 150.00,
    discount: 10,
    rating: 4.4,
    reviewsCount: 1650,
    description: "Sugar Free Gold is a low-calorie sugar substitute made from Aspartame. It is ideal for diabetics, weight watchers, and fitness enthusiasts who want to avoid sugar calories.",
    benefits: "1 pellet is equivalent in sweetness to 1 teaspoon of sugar but contains only 0.4 calories.",
    dosage: "Add pellets to tea, coffee, milk, or juices as per taste requirements.",
    sideEffects: "Not recommended for children and pregnant women. Safe for diabetics.",
    usage: "Dissolve easily in hot or cold beverages.",
    composition: "Aspartame, Bulking Agents",
    manufacturer: "Zydus Wellness Ltd",
    category: "Diabetes Care",
    image: "https://seo-cdn.pharmeasy.in/production/ecebb867-a80d-4026-9dc1-39fb02321a79.webp",
    prescriptionRequired: false,
    stock: 310
  },
  {
    id: "p18",
    uses: "Natural regulation of blood glucose levels, detoxifying the blood, and supporting healthy metabolism.",
    precautions: "Consult a doctor if you are already taking blood-sugar-lowering medicines to avoid hypoglycemia (low sugar).",
    name: "Kapiva Karela Jamun Juice",
    brand: "Kapiva",
    price: 299.00,
    discount: 20,
    rating: 4.3,
    reviewsCount: 1220,
    description: "Kapiva Karela Jamun Juice is a healthy blend of fresh Karela (Bitter Gourd) and Jamun (Black Plum) seeds. It is formulated to naturally regulate blood sugar levels and improve metabolic health.",
    benefits: "Aids in managing blood sugar levels, improves digestion, purifies blood, and boosts energy levels.",
    dosage: "Mix 30ml of juice in a glass of water and consume daily on an empty stomach in the morning.",
    sideEffects: "Mild stomach discomfort if taken in excess.",
    usage: "Shake well. Drink empty stomach. Maintain a healthy diet alongside.",
    composition: "Fresh Karela Juice 60%, Jamun Seed Extract 40%",
    manufacturer: "Adret Retail Pvt Ltd (Kapiva)",
    category: "Diabetes Care",
    image: "https://cdn01.pharmeasy.in/dam/products_otc/I10590/kapiva-karela-jamun-juice-1l-natural-juice-made-from-fresh-karela-and-jamun-seeds-6.5-1696408556.jpg",
    prescriptionRequired: false,
    stock: 140
  },
  {
    id: "p19",
    uses: "Drawing capillary blood samples for glucose testing or other blood tests.",
    precautions: "Sterile for single use only. Never reuse lancets to avoid pain and infection. Dispose of carefully in sharps bin.",
    name: "Dr. Morepen Lancets (100s)",
    brand: "Dr. Morepen",
    price: 180.00,
    discount: 25,
    rating: 4.5,
    reviewsCount: 1100,
    description: "Dr. Morepen sterile lancets are designed for use with most standard lancing devices to draw blood samples for glucose testing.",
    benefits: "Ultra-thin, tri-bevel needle tip minimizes pain during skin puncture. Sterilized for hygiene.",
    dosage: "Use a fresh sterile lancet for every test. Never reuse a lancet.",
    sideEffects: "None. Discard properly in a sharps container.",
    usage: "Insert into lancing device, twist off protective cap, select depth, and trigger.",
    composition: "100 Sterile Round Lancets",
    manufacturer: "Morepen Laboratories",
    category: "Diabetes Care",
    image: "https://onemg.gumlet.io/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/602f592c349c4a60b2e1f39e987b75f1.jpg",
    prescriptionRequired: false,
    stock: 180
  },
  {
    id: "p20",
    uses: "Intense hydration for dry, cracked skin, improving circulation, and preventing foot infections in diabetics.",
    precautions: "For external use only. Do not apply on open wounds or between the toes to avoid moisture buildup.",
    name: "Diabetic Foot Care Cream",
    brand: "FootSafe",
    price: 240.00,
    discount: 15,
    rating: 4.6,
    reviewsCount: 840,
    description: "A specially formulated cream to hydrate dry, cracked skin, improve blood circulation, and prevent neuropathy complications in diabetic feet.",
    benefits: "Prevents skin infections, heals deep heel cracks, reduces burning sensations, and increases skin elasticity.",
    dosage: "Apply twice daily, once after bathing and once before bedtime.",
    sideEffects: "None reported. Avoid applying between toes.",
    usage: "Wash feet thoroughly, pat dry, and massage the cream gently over feet and ankles.",
    composition: "L-Arginine, Urea, Shea Butter, Tea Tree Oil",
    manufacturer: "Hindustan Health Products",
    category: "Diabetes Care",
    image: "https://onemg.gumlet.io/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/cropped/hq2wzvgbxb5pph5dmnw9.jpg",
    prescriptionRequired: false,
    stock: 110
  },

  // --- Category: Health Supplements ---
  {
    id: "p21",
    uses: "Bone health support, prevention of osteoporosis, and meeting calcium and Vitamin D deficiencies.",
    precautions: "Drink plenty of water. Avoid taking iron supplements or tetracycline antibiotics within 2 hours of calcium intake.",
    name: "Calcimax 500 Tablet",
    brand: "Meyer Organics",
    price: 185.00,
    discount: 10,
    rating: 4.7,
    reviewsCount: 2200,
    description: "Calcimax 500 is a calcium supplement enriched with Vitamin D3, Magnesium, and Zinc. It helps support bone density, joint health, and muscle strength.",
    benefits: "Promotes bone mineral density, prevents osteoporosis, strengthens teeth, and enhances calcium absorption.",
    dosage: "1 tablet daily after meals or as advised by your healthcare practitioner.",
    sideEffects: "Constipation, mild gas, or bloating in rare instances.",
    usage: "Swallow whole. Best absorbed when taken with meals.",
    composition: "Elemental Calcium 500mg, Vitamin D3 250 IU, Magnesium 90mg, Zinc 7.5mg",
    manufacturer: "Meyer Organics Pvt Ltd",
    category: "Health Supplements",
    image: "https://cdn01.pharmeasy.in/dam/products_otc/031531/calcimax-500-health-supplement-tablets-500-mg-of-calcium-box-of-30-6.1-1702961575.jpg",
    prescriptionRequired: false,
    stock: 290
  },
  {
    id: "p22",
    uses: "Daily nutritional support, countering fatigue, boosting physical stamina, focus, and general immunity.",
    precautions: "Take after breakfast or lunch. Not recommended for children. Take a 15-day break after 3 months of continuous use.",
    name: "Revital H Capsule for Men",
    brand: "Sun Pharma",
    price: 310.00,
    discount: 12,
    rating: 4.6,
    reviewsCount: 3950,
    description: "Revital H is a daily health supplement containing a combination of Ginseng, 10 Vitamins, and 9 Minerals. It is designed to boost energy, improve focus, and build immunity.",
    benefits: "Fights fatigue, improves physical endurance, enhances mental alertness, and supports overall well-being.",
    dosage: "1 capsule daily with a glass of water after breakfast or lunch.",
    sideEffects: "Mild headache or stomach upset if taken empty stomach.",
    usage: "Take a break of 15 days after 3 months of continuous consumption.",
    composition: "Ginseng Extract 42.5mg, Vitamin A, B-Complex, C, D3, E, Iron, Zinc, Calcium",
    manufacturer: "Sun Pharmaceutical Industries Ltd",
    category: "Health Supplements",
    image: "https://onemg.gumlet.io/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/bc95ea846ac04cb4965fa4dba1452ef1.jpg",
    prescriptionRequired: false,
    stock: 350
  },
  {
    id: "p23",
    uses: "Support for heart health, joint flexibility, cognitive function, and healthy skin and vision.",
    precautions: "Consult doctor if you are taking blood thinners like warfarin. Discontinue if you experience fishy burps.",
    name: "Salmon Omega-3 Fish Oil",
    brand: "TrueBasics",
    price: 899.00,
    discount: 25,
    rating: 4.8,
    reviewsCount: 1540,
    description: "TrueBasics Salmon Omega-3 provides high-quality EPA and DHA extracted from cold-water salmon. The softgels are enteric-coated to prevent fishy aftertaste.",
    benefits: "Supports heart health, improves joint flexibility, enhances brain function, and promotes healthy skin and eyes.",
    dosage: "1-2 softgels daily after dinner or as advised.",
    sideEffects: "None. Avoid if allergic to fish.",
    usage: "Swallow the capsule whole with water. Do not chew.",
    composition: "Fish Oil 1000mg yielding EPA 360mg and DHA 240mg",
    manufacturer: "TrueBasics India",
    category: "Health Supplements",
    image: "https://onemg.gumlet.io/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/db6abf87b0cf4ee99b9bbb81fe39f6de.jpg",
    prescriptionRequired: false,
    stock: 120
  },
  {
    id: "p24",
    uses: "Immunity booster, prevention of scurvy, antioxidant defense, and skin collagen synthesis support.",
    precautions: "Chew the tablet fully before swallowing. Do not exceed 1 tablet daily unless recommended by a physician.",
    name: "Limcee Vitamin C Chewable",
    brand: "Abbott",
    price: 25.00,
    discount: 5,
    rating: 4.7,
    reviewsCount: 5800,
    description: "Limcee Chewable tablets are a orange-flavored formulation of Vitamin C. It is a powerful antioxidant that boosts immunity, prevents scurvy, and aids skin repair.",
    benefits: "Enhances immune defense, aids collagen synthesis for skin, accelerates wound healing, and helps iron absorption.",
    dosage: "Chew 1 tablet daily or as recommended by the physician.",
    sideEffects: "Diarrhea or abdominal cramps if consumed in mega doses.",
    usage: "Chew the tablet fully before swallowing. Do not swallow it whole.",
    composition: "Ascorbic Acid (Vitamin C) IP 500mg",
    manufacturer: "Abbott India Ltd",
    category: "Health Supplements",
    image: "https://onemg.gumlet.io/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/hmii4zhmjzmsgl1qcyy3.jpg",
    prescriptionRequired: false,
    stock: 650
  },
  {
    id: "p25",
    uses: "Muscle recovery, building lean mass, and dietary protein supplementation for athletes and fitness enthusiasts.",
    precautions: "Consult a physician if you have pre-existing kidney disease. Ensure adequate water intake throughout the day.",
    name: "MuscleBlaze Whey Protein (1kg)",
    brand: "MuscleBlaze",
    price: 2499.00,
    discount: 18,
    rating: 4.6,
    reviewsCount: 2900,
    description: "MuscleBlaze Biozyme Whey Protein provides high-quality protein per scoop, clinically tested for 50% higher protein absorption and 35% lower stomach discomfort.",
    benefits: "Enhances muscle recovery, builds lean muscle mass, reduces muscle breakdown, and delivers 25g protein per scoop.",
    dosage: "Mix 1 scoop (33g) in 200ml of cold water or milk. Consume post-workout.",
    sideEffects: "Bloating (rare). Consult doctor if lactose intolerant.",
    usage: "Shake vigorously in a shaker for 30 seconds until fully mixed.",
    composition: "Whey Protein Concentrate, Digestive Enzymes",
    manufacturer: "Bright Lifecare Pvt Ltd",
    category: "Health Supplements",
    image: "https://cdn01.pharmeasy.in/dam/products_otc/N54669/muscleblaze-biozyme-performance-whey-protein-powder-rich-chocolate-1kg-25g-protein-6.13-1778497019.jpg",
    prescriptionRequired: false,
    stock: 75
  },
  {
    id: "p26",
    uses: "Multivitamin support for immune strength, recovery from illness, and healthy metabolic cellular growth.",
    precautions: "Take after meals. Do not exceed the recommended daily allowance. Safe for long-term daily use.",
    name: "Zincovit Tablets (15s)",
    brand: "Apex Labs",
    price: 110.00,
    discount: 10,
    rating: 4.8,
    reviewsCount: 6800,
    description: "Zincovit Tablet is a premium multivitamin and multimineral supplement with Grape Seed Extract. It is highly recommended to improve immunity and support recovery during convalescence.",
    benefits: "Boosts immune responses, counters nutritional deficiencies, helps fight fatigue, and aids healthy cell growth.",
    dosage: "1 tablet daily after food or as directed.",
    sideEffects: "None reported when taken in standard doses.",
    usage: "Swallow with water. Best taken after lunch or dinner.",
    composition: "Vitamins A, B-Complex, C, D3, E, Zinc, Copper, Selenium, Grape Seed Extract",
    manufacturer: "Apex Laboratories Pvt Ltd",
    category: "Health Supplements",
    image: "https://onemg.gumlet.io/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/70e5bc9b023b47a7927bd4c28deaf751.jpg",
    prescriptionRequired: false,
    stock: 450
  },
  {
    id: "p27",
    uses: "Treatment of neuropathic pain, tingling, numbness, nerve damage, and Vitamin B-complex deficiencies.",
    precautions: "Swallow whole with water. Riboflavin may cause harmless bright yellow urine. Consult doctor if symptoms persist.",
    name: "Neurobion Forte Tablet",
    brand: "Procter & Gamble",
    price: 38.00,
    discount: 5,
    rating: 4.7,
    reviewsCount: 3400,
    description: "Neurobion Forte is the most trusted Vitamin B-complex supplement. It is crucial for maintaining healthy nerves, red blood cells, and overall metabolic functions.",
    benefits: "Relieves nerve pain, burning sensations, numbness, strengthens the immune system, and manages vitamin deficiencies.",
    dosage: "1 tablet daily or as advised by your physician.",
    sideEffects: "Mild yellow coloration of urine (harmless, due to Riboflavin).",
    usage: "Swallow whole. Do not chew or crush.",
    composition: "Thiamine (B1) 10mg, Riboflavin (B2) 10mg, Pyridoxine (B6) 3mg, Cyanocobalamin (B12) 15mcg, Niacinamide 45mg",
    manufacturer: "P&G Health Ltd",
    category: "Health Supplements",
    image: "https://onemg.gumlet.io/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/cropped/z8mu0h1bejqxaqhvdq0l.jpg",
    prescriptionRequired: false,
    stock: 520
  },

  // --- Category: Baby Care ---
  {
    id: "p28",
    uses: "Moisturizing and protecting delicate baby skin, keeping it soft, supple, and healthy.",
    precautions: "For external use only. Perform a patch test on a small skin area before full application to check for allergies.",
    name: "Himalaya Baby Lotion (400ml)",
    brand: "Himalaya",
    price: 280.00,
    discount: 15,
    rating: 4.6,
    reviewsCount: 1950,
    description: "Himalaya Baby Lotion is formulated to keep baby's skin soft, supple, and protected. Infused with Olive Oil and Almond Oil, it provides intense, gentle moisturization.",
    benefits: "Free from parabens, synthetic colors, and phthalates. Clinically safe and hypoallergenic.",
    dosage: "Apply as needed, especially after bathing.",
    sideEffects: "None. Perform a patch test before first use.",
    usage: "Apply gently over baby's body, avoiding eyes and mouth.",
    composition: "Olive Oil, Country Mallow, Licorice, Almond Oil",
    manufacturer: "The Himalaya Drug Company",
    category: "Baby Care",
    image: "https://cdn.pixelbin.io/v2/plain-cake-860195/netmed/wrkr/products/assets/item/free/original/6mbDXiqYnc-himalaya_baby_lotion_400_ml_0.jpg",
    prescriptionRequired: false,
    stock: 160
  },
  {
    id: "p29",
    uses: "Absorbing excess skin moisture, reducing diaper friction, and keeping baby skin fresh and dry.",
    precautions: "Keep powder away from baby's nose and mouth to prevent inhalation, which can cause breathing problems.",
    name: "Johnson's Baby Powder (200g)",
    brand: "Johnson & Johnson",
    price: 160.00,
    discount: 10,
    rating: 4.5,
    reviewsCount: 3100,
    description: "Johnson's Baby Powder protects baby's skin from excess moisture and friction, keeping it dry, fresh, and comfortably soft.",
    benefits: "Clinically proven mildness. Clean, classic baby-fresh scent. Reduces friction rashes.",
    dosage: "Apply after diaper changes or baths.",
    sideEffects: "None. Keep powder away from baby's nose and mouth to avoid inhalation.",
    usage: "Shake powder directly onto your hand, away from the baby, then smooth gently onto skin.",
    composition: "Talc, Fragrance",
    manufacturer: "Johnson & Johnson Ltd",
    category: "Baby Care",
    image: "https://cdn.pixelbin.io/v2/plain-cake-860195/netmed/wrkr/products/pictures/item/free/original/IVWNKyNYY0-johnson_s_baby_powder_50_gm_0.jpg",
    prescriptionRequired: false,
    stock: 220
  },
  {
    id: "p30",
    uses: "Gentle soap-free skin cleansing for babies, maintaining healthy skin pH 5.5 mantle.",
    precautions: "Dermatologically tested. Avoid contact with eyes. Rinse thoroughly with lukewarm water.",
    name: "Sebamed Baby Gentle Wash",
    brand: "Sebamed",
    price: 450.00,
    discount: 8,
    rating: 4.8,
    reviewsCount: 1400,
    description: "Sebamed Baby Gentle Wash has a pH of 5.5, which supports the development of the skin's natural protective acid mantle. It is extremely mild and soap-free.",
    benefits: "No tears formula. Soap-free, alkali-free. Protects against dryness and irritation.",
    dosage: "Use daily during bathing.",
    sideEffects: "Hypoallergenic. No known side effects.",
    usage: "Apply a few drops to hands, massage gently onto baby's wet skin, and rinse thoroughly.",
    composition: "Water, Cocamidopropyl Betaine, Vernix-matching lipids",
    manufacturer: "Sebamed Germany",
    category: "Baby Care",
    image: "https://onemg.gumlet.io/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/8a8df8400d3949ba9a0cc3ab695165a7.jpg",
    prescriptionRequired: false,
    stock: 90
  },
  {
    id: "p31",
    uses: "Keeping baby dry, preventing leakages, and protecting baby skin from wetness rashes.",
    precautions: "Change diapers promptly upon wetting. Clean and dry the diaper area thoroughly before putting on a new diaper.",
    name: "Pampers Premium Care Diapers (M, 48s)",
    brand: "Pampers",
    price: 799.00,
    discount: 20,
    rating: 4.7,
    reviewsCount: 4120,
    description: "Pampers Premium Care Diapers feature an ultra-absorbent core and cotton-like softness to provide 5-star skin protection for babies.",
    benefits: "Wetness indicator changes blue when wet. Stretchy sides for active fit. Breathable micropores.",
    dosage: "Change diapers every 3-4 hours or immediately when soiled.",
    sideEffects: "Avoid diaper rash by maintaining hygiene and applying rash cream.",
    usage: "Slip onto baby, align waist tapes, and fasten securely.",
    composition: "Absorbent polymer, Breathable backsheet, Aloe Vera lotion coating",
    manufacturer: "Procter & Gamble",
    category: "Baby Care",
    image: "https://onemg.gumlet.io/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/9eb01d8aa6c842ce9577f60d92987270.jpg",
    prescriptionRequired: false,
    stock: 130
  },
  {
    id: "p32",
    uses: "Cleansing baby's face, hands, diaper area, and body gently during travel or diaper changes.",
    precautions: "Close the resealable label tightly after every use to prevent wipes from drying out. Store in a cool place.",
    name: "Mamaearth Organic Bamboo Wipes",
    brand: "Mamaearth",
    price: 249.00,
    discount: 10,
    rating: 4.6,
    reviewsCount: 2200,
    description: "Mamaearth Organic Bamboo Wipes are biodegradable baby wipes made from organic bamboo fibers. Gentle on skin, tough on dirt.",
    benefits: "100% natural, alcohol-free, travel-friendly packaging. Infused with Aloe Vera and Almond Oil.",
    dosage: "Use as needed to wipe baby's face, hands, or diaper area.",
    sideEffects: "None. Suitable for sensitive skin.",
    usage: "Pull out a single wipe, clean gently, and reseal the pack cover immediately.",
    composition: "Bamboo fibers, Aloe Vera Extract, Almond Oil, Tea Tree Oil",
    manufacturer: "Honasa Consumer Pvt Ltd (Mamaearth)",
    category: "Baby Care",
    image: "https://cdn01.pharmeasy.in/dam/products_otc/D87539/mamaearth-organic-bamboo-wipes-packet-of-72-s-6.1-1641788941.jpg",
    prescriptionRequired: false,
    stock: 240
  },
  {
    id: "p33",
    uses: "Hydrating baby skin, calming muscles, and promoting healthy blood circulation through gentle massage.",
    precautions: "Avoid contact with baby's eyes, ears, and mouth. Warm the oil between your palms before applying.",
    name: "Mothercare Baby Massage Oil",
    brand: "Mothercare",
    price: 350.00,
    discount: 15,
    rating: 4.5,
    reviewsCount: 650,
    description: "Infused with calming chamomile and vitamin E, this massage oil hydrates baby's delicate skin while strengthening muscles.",
    benefits: "Non-greasy, fast-absorbing, dermatologically tested, promotes healthy sleep patterns.",
    dosage: "Apply daily before bath.",
    sideEffects: "None reported. Avoid facial contact.",
    usage: "Pour a few drops on palms, rub to warm, and massage baby's limbs in circular motions.",
    composition: "Mineral oil, Chamomile extract, Vitamin E acetate",
    manufacturer: "Mothercare PLC",
    category: "Baby Care",
    image: "https://images.apollo247.in/pub/media/catalog/product/m/o/mot0085_1.jpg",
    prescriptionRequired: false,
    stock: 80
  },

  // --- Category: Personal Care ---
  {
    id: "p34",
    uses: "Gentle skin cleansing for sensitive, dry, or acne-prone skin without causing dryness.",
    precautions: "Dermatologist recommended. Safe for daily use. Can be used with or without water.",
    name: "Cetaphil Gentle Skin Cleanser",
    brand: "Galderma",
    price: 395.00,
    discount: 8,
    rating: 4.8,
    reviewsCount: 5100,
    description: "Cetaphil Gentle Skin Cleanser is a dermatologist-recommended soap-free formula that cleanses skin deeply without stripping natural oils.",
    benefits: "Hypoallergenic, non-comedogenic, locks in skin moisture, ideal for all skin types, including sensitive skin.",
    dosage: "Apply morning and evening.",
    sideEffects: "None.",
    usage: "Apply with water and rinse, or apply and wipe off gently with a cotton pad without water.",
    composition: "Water, Cetyl Alcohol, Propylene Glycol, Sodium Lauryl Sulfate",
    manufacturer: "Galderma India Pvt Ltd",
    category: "Personal Care",
    image: "https://cdn01.pharmeasy.in/dam/products_otc/I44087/cetaphil-gentle-skin-cleanser-face-body-1l-6.09-1768556579.jpg",
    prescriptionRequired: false,
    stock: 190
  },
  {
    id: "p35",
    uses: "Lightweight oil-free hydration for face and neck, locking in skin moisture for 72 hours.",
    precautions: "For external use only. Apply on clean, dry skin. Avoid direct contact with eyes.",
    name: "Neutrogena Hydro Boost Gel",
    brand: "Johnson & Johnson",
    price: 950.00,
    discount: 12,
    rating: 4.7,
    reviewsCount: 3800,
    description: "Neutrogena Hydro Boost Water Gel is a unique oil-free moisturizer with Hyaluronic Acid that hydrates dry skin and keeps it smooth and glowing.",
    benefits: "72 hours hydration lock. Absorbs instantly. Non-sticky, lightweight water gel.",
    dosage: "Apply twice daily, after cleansing.",
    sideEffects: "None. Safe for acne-prone skin.",
    usage: "Apply evenly to face and neck. Massage in an upward direction.",
    composition: "Hyaluronic Acid, Glycerin, Olive Extract",
    manufacturer: "Neutrogena Corp",
    category: "Personal Care",
    image: "https://cdn01.pharmeasy.in/dam/products_otc/U53054/neutrogena-hydro-boost-hyaluronic-acid-serum-30ml-6.01-1778239048.jpg",
    prescriptionRequired: false,
    stock: 140
  },
  {
    id: "p36",
    uses: "Deep pore cleansing, regulating facial sebum, and preventing acne breakouts.",
    precautions: "Avoid contact with eyes. If irritation occurs, wash off immediately and discontinue use.",
    name: "Biotique Tea Tree Face Wash",
    brand: "Biotique",
    price: 135.00,
    discount: 10,
    rating: 4.4,
    reviewsCount: 2900,
    description: "Biotique Tea Tree Face Wash cleanses pores, regulates sebum production, and prevents acne breakouts with the goodness of natural botanical extracts.",
    benefits: "100% botanical extracts. Soap-free, paraben-free. Clarifies skin and lightens acne scars.",
    dosage: "Use twice daily, morning and night.",
    sideEffects: "Mild skin dryness in extremely dry skin types.",
    usage: "Lather on wet face, massage gently, and wash off with cool water.",
    composition: "Tea Tree Oil, Neem Bark, Pineapple Extract",
    manufacturer: "Bio Veda Action Research Co.",
    category: "Personal Care",
    image: "https://onemg.gumlet.io/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/mqzp2quddnhwg7gw3nrz.jpg",
    prescriptionRequired: false,
    stock: 310
  },
  {
    id: "p37",
    uses: "Effective hand hygiene, protecting against 99.9% of illness-causing germs and bacteria.",
    precautions: "For external use only. Avoid contact with eyes. In case of contact, rinse thoroughly with fresh water.",
    name: "Dettol Liquid Handwash Refill",
    brand: "Reckitt Benckiser",
    price: 99.00,
    discount: 10,
    rating: 4.7,
    reviewsCount: 6500,
    description: "Dettol Liquid Handwash protects against 100 illness-causing germs. Specially formulated with skin moisturizers.",
    benefits: "99.9% germ protection. Dermatologically tested. Keeps hands clean and hydrated.",
    dosage: "Use whenever hands are dirty or before eating.",
    sideEffects: "For external use only. Avoid contact with eyes.",
    usage: "Press nozzle gently to get handwash, rub palms together with water to form lather, rinse thoroughly.",
    composition: "Salicylic Acid, Glycerin, Active Germicides",
    manufacturer: "Reckitt Benckiser India",
    category: "Personal Care",
    image: "https://cdn01.pharmeasy.in/dam/products_otc/I05060/dettol-liquid-handwash-refill-skincare-hand-wash-675ml-buy-1-get-1-free-6.09-1752756275.jpg",
    prescriptionRequired: false,
    stock: 450
  },
  {
    id: "p38",
    uses: "Daily protection from harmful UVA/UVB rays, preventing sun tan, pigmentation, and skin aging.",
    precautions: "Apply 20 minutes before sun exposure. Reapply every 3 hours if swimming or sweating.",
    name: "Lotus Sunscreen SPF 50",
    brand: "Lotus Herbals",
    price: 365.00,
    discount: 15,
    rating: 4.5,
    reviewsCount: 2700,
    description: "Lotus Safe Sun 3-in-1 Matte Look Daily Sunscreen SPF 50 protects skin from harmful UVA and UVB rays and gives a smooth matte finish.",
    benefits: "Protects against tanning, pigmentation, and premature aging. Non-greasy and sweat-proof.",
    dosage: "Apply 20 minutes before stepping out in the sun.",
    sideEffects: "None. Avoid eye contact.",
    usage: "Apply liberally on face, neck, and arms. Reapply every 3 hours if outdoors.",
    composition: "Birch Extract, Mallow Extract, Hops Extract",
    manufacturer: "Lotus Herbals Pvt Ltd",
    category: "Personal Care",
    image: "https://onemg.gumlet.io/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/2ab4188cac2e4634be9fc3002c55be93.jpg",
    prescriptionRequired: false,
    stock: 180
  },
  {
    id: "p39",
    uses: "Intense daily moisturization for face, hands, and body, leaving skin soft and refreshed.",
    precautions: "Non-greasy and fast-absorbing. Safe for daily use on all skin types.",
    name: "Nivea Soft Moisturizing Cream",
    brand: "Nivea",
    price: 190.00,
    discount: 10,
    rating: 4.6,
    reviewsCount: 3100,
    description: "Nivea Soft is an invigorating, fast-absorbing moisturizing cream containing Jojoba Oil and Vitamin E.",
    benefits: "Provides intensive refreshing hydration, leaves skin feeling soft and elastic.",
    dosage: "Apply whenever skin feels dry.",
    sideEffects: "None.",
    usage: "Scoop cream and rub gently into clean skin on face, hands, or body.",
    composition: "Jojoba Oil, Vitamin E Acetate, Purified Water",
    manufacturer: "Nivea India Pvt Ltd",
    category: "Personal Care",
    image: "https://onemg.gumlet.io/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/51cb4728ec3642a4b6e327d652e13bc5.jpg",
    prescriptionRequired: false,
    stock: 220
  },

  // --- Category: Medical Devices ---
  {
    id: "p40",
    uses: "Automatic tracking of blood pressure and pulse rate at home for cardiovascular health management.",
    precautions: "Sit quietly for 5 minutes before checking. Place cuff on bare arm at heart level. Avoid talking during measurement.",
    name: "Omron HEM 7120 BP Monitor",
    brand: "Omron",
    price: 1999.00,
    discount: 20,
    rating: 4.8,
    reviewsCount: 9200,
    description: "Omron HEM-7120 is a compact, fully automatic blood pressure monitor operating on the oscillometric principle. It measures blood pressure and pulse rate simply and quickly.",
    benefits: "One-touch operation. Intellisense technology for comfortable inflation. Detects irregular heartbeat.",
    dosage: "Use as needed to track blood pressure. Best checked when relaxed.",
    sideEffects: "None.",
    usage: "Wrap the arm cuff around the upper left arm, sit comfortably, and press the start button.",
    composition: "1 BP Monitor Unit, 1 Arm Cuff, 4 AA Batteries, Instruction Manual",
    manufacturer: "Omron Healthcare Co. Ltd",
    category: "Medical Devices",
    image: "https://onemg.gumlet.io/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/e5e4af99267941d5b5b355648c3ce7a1.jpg",
    prescriptionRequired: false,
    stock: 65
  },
  {
    id: "p41",
    uses: "Accurate measurement of body temperature to detect fever orally, underarm, or rectally.",
    precautions: "Clean the sensor tip with rubbing alcohol before and after use. Keep out of reach of young children.",
    name: "Dr. Trust Digital Thermometer",
    brand: "Dr. Trust",
    price: 220.00,
    discount: 15,
    rating: 4.6,
    reviewsCount: 3100,
    description: "Dr. Trust Digital Thermometer offers clinical-grade accuracy and speed in measuring body temperature orally, rectally, or under the armpit.",
    benefits: "Waterproof tip. Beep sound alert. Auto shut-off. Memory recall of last reading.",
    dosage: "Use when fever is suspected.",
    sideEffects: "Clean with rubbing alcohol before and after each use.",
    usage: "Place the metallic tip under tongue or in armpit, hold still until it beeps, and read display.",
    composition: "1 Digital Thermometer Unit, Plastic Storage Case",
    manufacturer: "Nureca Limited (Dr. Trust)",
    category: "Medical Devices",
    image: "https://cdn.pixelbin.io/v2/plain-cake-860195/netmed/wrkr/products/assets/item/free/original/bu1TAHqLpA-dr_trust_usa_non_contact_infrared_forehead_thermometer_ir_gun_603_0_0.jpg",
    prescriptionRequired: false,
    stock: 240
  },
  {
    id: "p42",
    uses: "Fingertip measurement of blood oxygen saturation (SpO2) and pulse rate levels.",
    precautions: "Keep hand still during measurement. Do not use on fingers with nail polish or cold hands as it may affect accuracy.",
    name: "Fingertip Pulse Oximeter",
    brand: "Dr. Morepen",
    price: 899.00,
    discount: 30,
    rating: 4.7,
    reviewsCount: 4200,
    description: "Fingertip Pulse Oximeter measures blood oxygen saturation (SpO2) and pulse rate instantly. Highly recommended for respiratory monitoring.",
    benefits: "Dual color OLED display. SpO2, Pulse Rate, and Pulse Bar graph. Low power consumption.",
    dosage: "Place on finger to measure SpO2 levels.",
    sideEffects: "Avoid movement during measurement for accurate reading.",
    usage: "Clip onto finger (preferably index), press button, and wait 5 seconds for readings.",
    composition: "1 Pulse Oximeter, 2 AAA Batteries, Lanyard",
    manufacturer: "Morepen Laboratories Ltd",
    category: "Medical Devices",
    image: "https://onemg.gumlet.io/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/o291ovg9uecjswn7wz1b.jpg",
    prescriptionRequired: false,
    stock: 120
  },
  {
    id: "p43",
    uses: "Converting liquid medication into a fine aerosol mist for direct inhalation into the lungs.",
    precautions: "Clean and sterilize all medication cups and masks after each use to prevent bacterial contamination.",
    name: "Philips Nebulizer Compressor",
    brand: "Philips Respironics",
    price: 2499.00,
    discount: 10,
    rating: 4.8,
    reviewsCount: 1500,
    description: "Philips Respironics InnoSpire Essence is a highly efficient compressor nebulizer system that provides fast, effective aerosol medication delivery.",
    benefits: "SideStream technology produces high-quality aerosol. Quick treatment times in under 6 minutes.",
    dosage: "As directed by physician using prescribed nebulizer medications.",
    sideEffects: "Clean mouthpiece/mask thoroughly after every use to prevent bacterial growth.",
    usage: "Fill medication cup, connect tubing, put on mask, turn on compressor, and inhale mist.",
    composition: "1 Compressor, 1 SideStream Nebulizer, Mouthpiece, Adult Mask, Pediatric Mask, Tubing",
    manufacturer: "Philips Healthcare",
    category: "Medical Devices",
    image: "https://cdn01.pharmeasy.in/dam/products_otc/H73062/philips-respironics-home-nebulizer-side-stream-disposable-ref-2350-6.3-1632781647.jpg",
    prescriptionRequired: false,
    stock: 45
  },
  {
    id: "p44",
    uses: "Facial steam therapy for opening skin pores, and steam inhalation for clearing blocked nasal passages.",
    precautions: "Maintain a safety distance of at least 20cm from the nozzle to avoid steam burns. Use clean water only.",
    name: "HealthSense Steamer Inhaler",
    brand: "HealthSense",
    price: 499.00,
    discount: 15,
    rating: 4.5,
    reviewsCount: 1980,
    description: "HealthSense Nano-Cure facial ionic steamer and steam inhaler provides deep penetration steam for nasal clearance and facial skincare.",
    benefits: "Instant nano-ionic steam in 40 seconds. Safe and quiet operation. Silent heating.",
    dosage: "Steam inhale for 5-10 minutes during nasal congestion or cold.",
    sideEffects: "Keep safe distance (at least 20cm) from steam outlet to prevent burns.",
    usage: "Fill measuring cup with distilled water, pour in tank, turn power switch on, and inhale.",
    composition: "1 Steamer Unit, 1 Inhaler Attachment, 1 Measuring Cup",
    manufacturer: "HealthSense India",
    category: "Medical Devices",
    image: "https://images-static.nykaa.com/media/catalog/product/3/f/3f1e86f691046939418_1.jpg",
    prescriptionRequired: false,
    stock: 140
  },
  {
    id: "p45",
    uses: "Precise measurement and tracking of body weight metrics at home.",
    precautions: "Place scale on a hard, flat surface. Step on with bare feet and stand still until reading stabilizes.",
    name: "Digital Body Weighing Scale",
    brand: "HealthSense",
    price: 999.00,
    discount: 25,
    rating: 4.6,
    reviewsCount: 2900,
    description: "Ultra-precise digital weighing scale with high-grade tempered glass and instant step-on technology.",
    benefits: "Sturdy tempered glass platform, blue backlight LCD display, high-precision sensors.",
    dosage: "Use weekly or daily to track body weight metrics.",
    sideEffects: "Place on hard, flat surface. Not for carpets.",
    usage: "Step on the scale with bare feet, stand still, and read the weight display.",
    composition: "1 Weighing Scale, 2 AAA Batteries, Manual",
    manufacturer: "HealthSense India",
    category: "Medical Devices",
    image: "https://onemg.gumlet.io/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/37dc513a86ea42668b2d0c16d8924620.jpg",
    prescriptionRequired: false,
    stock: 100
  },

  // --- Category: Ayurvedic Products ---
  {
    id: "p46",
    uses: "Daily health tonic to boost immunity, fight seasonal infections, and support respiratory health.",
    precautions: "Not recommended in original form for severe diabetics (choose sugar-free variants instead). Consume with warm milk.",
    name: "Dabur Chyawanprash (1kg)",
    brand: "Dabur",
    price: 375.00,
    discount: 10,
    rating: 4.8,
    reviewsCount: 8200,
    description: "Dabur Chyawanprash is a time-tested Ayurvedic formulation of more than 40 herbs, including Amla, Giloy, Ashwagandha, and Pippali. It boosts general immunity and physical strength.",
    benefits: "Provides double immunity. Fights day-to-day infections. Stimulates digestion and respiratory health.",
    dosage: "1 teaspoonful (approx. 12g) twice daily for adults. 1/2 teaspoonful for children.",
    sideEffects: "Safe for all ages. Diabetics should prefer Sugar-Free variants.",
    usage: "Can be taken directly or mixed with warm milk/water.",
    composition: "Amla, Giloy, Ashwagandha, Pippali, Shatavari, Cardamom",
    manufacturer: "Dabur India Limited",
    category: "Ayurvedic Products",
    image: "https://onemg.gumlet.io/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/48d3071163364bf7a89df840a006d404.jpg",
    prescriptionRequired: false,
    stock: 310
  },
  {
    id: "p47",
    uses: "Adaptogenic support to manage daily stress, anxiety, improve energy levels, and boost general vitality.",
    precautions: "Consult doctor if you are taking thyroid medications or immunosuppressants. Safe for long-term daily use.",
    name: "Himalaya Ashwagandha Tablets",
    brand: "Himalaya",
    price: 165.00,
    discount: 5,
    rating: 4.7,
    reviewsCount: 3400,
    description: "Himalaya Ashwagandha contains pure root extract of Ashwagandha (Withania somnifera). It is a powerful adaptogen that helps the body manage stress and anxiety.",
    benefits: "Reduces cortisol (stress hormone) levels. Boosts vitality, strength, and immunity. Supports restful sleep.",
    dosage: "1-2 tablets twice daily with water or warm milk, or as recommended by the Ayurvedic doctor.",
    sideEffects: "Mild drowsiness if taken in high doses.",
    usage: "Swallow with water or milk. Regular intake yields best adaptogenic results.",
    composition: "Ashwagandha (Withania somnifera) root extract 250mg",
    manufacturer: "The Himalaya Drug Company",
    category: "Ayurvedic Products",
    image: "https://onemg.gumlet.io/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/fmtzd2ajexw37xyidgwq.jpg",
    prescriptionRequired: false,
    stock: 280
  },
  {
    id: "p48",
    uses: "Ayurvedic digestive support, relief from chronic constipation, and colon detoxification.",
    precautions: "Take with warm water at bedtime. Avoid high doses to prevent loose motions.",
    name: "Baidyanath Triphala Churna",
    brand: "Baidyanath",
    price: 95.00,
    discount: 5,
    rating: 4.5,
    reviewsCount: 1650,
    description: "Baidyanath Triphala Churna is a classical Ayurvedic formulation consisting of Haritaki, Bibhitaki, and Amalaki. It acts as an excellent laxative and colon cleanser.",
    benefits: "Relieves chronic constipation, aids digestion, detoxifies the colon, and improves bowel habits.",
    dosage: "1 teaspoonful (5g) with warm water at bedtime.",
    sideEffects: "Loose stools if consumed in very high quantities.",
    usage: "Stir powder in lukewarm water and drink immediately before sleeping.",
    composition: "Haritaki (Terminalia chebula), Bibhitaki (Terminalia bellirica), Amalaki (Emblica officinalis) in equal proportions",
    manufacturer: "Shree Baidyanath Ayurved Bhawan Pvt Ltd",
    category: "Ayurvedic Products",
    image: "https://cdn01.pharmeasy.in/dam/products_otc/B25601/baidyanath-triphala-churna-helps-relieve-constipation-quick-acidity-gas-relief-240gms-6.1-1641789435.jpg",
    prescriptionRequired: false,
    stock: 400
  },
  {
    id: "p49",
    uses: "Natural blood purification, detoxification, improving liver health, and managing skin acne.",
    precautions: "Dilute with water as it is very bitter. Avoid consumption during pregnancy and lactation.",
    name: "Kapiva Organic Neem Juice",
    brand: "Kapiva",
    price: 249.00,
    discount: 15,
    rating: 4.4,
    reviewsCount: 920,
    description: "Kapiva Organic Neem Juice is made from fresh, organic Neem leaves sourced from Rajasthan. It serves as a natural blood purifier and detoxifier.",
    benefits: "Purifies blood, treats acne and skin infections from within, improves liver health, and regulates blood sugar.",
    dosage: "Dilute 30ml of juice in a glass of water. Consume on an empty stomach in the morning.",
    sideEffects: "Very bitter taste. High doses should be avoided by pregnant women.",
    usage: "Shake well. Drink empty stomach. Dilute with water to reduce bitterness.",
    composition: "100% Organic Neem Leaf Juice",
    manufacturer: "Adret Retail Pvt Ltd (Kapiva)",
    category: "Ayurvedic Products",
    image: "https://cdn01.pharmeasy.in/dam/products_otc/I10610/kapiva-rajasthani-neem-juice-1l-natural-juice-made-from-fresh-neem-leaves-healthy-hair-skin-6.6-1670588428.jpg",
    prescriptionRequired: false,
    stock: 150
  },
  {
    id: "p50",
    uses: "Soothes sun burns, hydrates dry skin, reduces skin inflammation, and conditions hair.",
    precautions: "For external use only. Discontinue if skin rash or allergic irritation occurs.",
    name: "Patanjali Aloe Vera Gel",
    brand: "Patanjali",
    price: 90.00,
    discount: 5,
    rating: 4.6,
    reviewsCount: 4800,
    description: "Patanjali Aloe Vera Gel is a pure, multi-purpose gel extracted from mature Aloe Vera leaves. It is designed to soothe, hydrate, and heal both skin and hair.",
    benefits: "Moisturizes skin, treats sunburns, reduces acne inflammation, and acts as a lightweight hair conditioner.",
    dosage: "Apply liberally on skin or scalp as needed.",
    sideEffects: "None. Suitable for all skin types.",
    usage: "Massage gently into skin or scalp until fully absorbed. Leave on or rinse off as desired.",
    composition: "Aloe Vera Inner Leaf Extract 90%, Gel base and preservatives",
    manufacturer: "Patanjali Ayurved Limited",
    category: "Ayurvedic Products",
    image: "https://cdn01.pharmeasy.in/dam/products_otc/I05972/patanjali-aloevera-tube-of-60ml-gel-2-1669655097.jpg",
    prescriptionRequired: false,
    stock: 380
  }
];

// If running in node, export the module (just in case for validation or bundlers), but keep it globally available in browsers.
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { PRODUCTS };
}
